[package]
name = "web-stack-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
hypertext = { version = "0.5.2", features = ["axum"] }
tokio = { version = "1.42.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
